def solve(grid: list[list[int]]) -> list[list[int]]:
    """
    Observation:
    1. Input is a grid of varying dimensions (HxW)
    2. Output is always a 20x20 grid
    3. The first min(H,20) rows: columns 0 to W-1 copy from input directly
    4. The remaining columns are filled by tiling/repeating the input
    5. Rows beyond H are generated by repeating/tiling pattern

    Procedure:
    1. Initialize 20x20 output grid
    2. Fill by tiling the input in both dimensions
    """

    h, w = len(grid), len(grid[0])
    TARGET = 20

    # Initialize output grid by tiling the input
    result = [[grid[r % h][c % w] for c in range(TARGET)] for r in range(TARGET)]

    return result
