def solve(grid: list[list[int]]) -> list[list[int]]:
    """
    Observation:
    1. Input has a rectangular frame made of one color (e.g., 9, 3, 4)
    2. Inside the frame is a pattern using a non-8 color and 8s as background
    3. Output extracts the frame and transforms the interior pattern
    4. The interior is divided into horizontal bands with the non-8 color appearing in different contiguous column sections
    5. Patterns are generated by selecting contiguous ranges of column parts

    Procedure:
    1. Find the rectangular frame (bounding box of frame color)
    2. Extract the interior
    3. Identify the non-8, non-frame color (the "special" color)
    4. Divide the interior columns into equal parts
    5. Generate row patterns where special color appears in contiguous column ranges
    6. Determine the number of output groups based on divisibility
    7. Add the frame border around the transformed interior
    """

    rows, cols = len(grid), len(grid[0])

    # Find the frame by looking for a rectangular border
    frame_color = None
    min_r, max_r, min_c, max_c = None, None, None, None

    for r in range(rows):
        for c in range(cols):
            if grid[r][c] != 8:
                color = grid[r][c]
                r1, c1 = r, c
                while c1 > 0 and grid[r1][c1 - 1] == color:
                    c1 -= 1
                c2 = c
                while c2 < cols - 1 and grid[r1][c2 + 1] == color:
                    c2 += 1
                r2 = r
                while r2 < rows - 1 and grid[r2 + 1][c1] == color:
                    r2 += 1

                if r2 > r1 + 2 and c2 > c1 + 2:
                    is_frame = True
                    for check_c in range(c1, c2 + 1):
                        if grid[r1][check_c] != color or grid[r2][check_c] != color:
                            is_frame = False
                            break
                    if is_frame:
                        for check_r in range(r1, r2 + 1):
                            if grid[check_r][c1] != color or grid[check_r][c2] != color:
                                is_frame = False
                                break

                    if is_frame:
                        frame_color = color
                        min_r, max_r, min_c, max_c = r1, r2, c1, c2
                        break
            if frame_color is not None:
                break
        if frame_color is not None:
            break

    # Extract interior
    interior = []
    for r in range(min_r + 1, max_r):
        row = []
        for c in range(min_c + 1, max_c):
            row.append(grid[r][c])
        interior.append(row)

    interior_rows = len(interior)
    interior_cols = len(interior[0]) if interior else 0

    # Find the special color
    special_color = None
    for row in interior:
        for val in row:
            if val != 8 and val != frame_color:
                special_color = val
                break
        if special_color is not None:
            break

    # Determine column division
    num_parts = 3 if interior_cols % 3 == 0 else (4 if interior_cols % 4 == 0 else 2)
    cols_per_part = interior_cols // num_parts

    # Determine number of output groups
    # Try to use interior_rows / cols_per_part if it divides evenly
    if interior_rows % cols_per_part == 0:
        num_groups = interior_rows // cols_per_part
    else:
        # Otherwise try common divisors
        num_groups = None
        for candidate in [3, 4, 2, 5, 6]:
            if interior_rows % candidate == 0:
                num_groups = candidate
                break
        if num_groups is None:
            num_groups = interior_rows

    rows_per_group = interior_rows // num_groups

    # Generate patterns based on contiguous column ranges
    def make_pattern(start_part, num_consecutive_parts):
        """Create a pattern with special color in consecutive parts"""
        pattern = []
        for part_idx in range(num_parts):
            if start_part <= part_idx < start_part + num_consecutive_parts:
                pattern.extend([special_color] * cols_per_part)
            else:
                pattern.extend([8] * cols_per_part)
        return pattern

    # Generate pattern ranges based on num_parts and num_groups
    patterns = []

    if num_parts == 3:
        if num_groups == 3:
            # Pattern: parts [0,1], [1,2], [0]
            patterns.append(make_pattern(0, 2))
            patterns.append(make_pattern(1, 2))
            patterns.append(make_pattern(0, 1))
        elif num_groups == 4:
            # Pattern: parts [0,1,2], [2], [0,1], [1,2]
            patterns.append(make_pattern(0, 3))
            patterns.append(make_pattern(2, 1))
            patterns.append(make_pattern(0, 2))
            patterns.append(make_pattern(1, 2))
        else:
            # Default: use length N-1 patterns
            for start in range(num_parts):
                if start + (num_parts - 1) <= num_parts:
                    patterns.append(make_pattern(start, num_parts - 1))
            if len(patterns) < num_groups:
                patterns.append(make_pattern(0, 1))
    elif num_parts == 4 and interior_cols % 4 == 0 and num_groups == 3:
        # Special case: columns divisible by 4 with symmetric 3-part division
        # Use symmetric pattern: side + middle + side (e.g., 2+4+2 for 8 cols)
        side = interior_cols // 4
        middle = interior_cols // 2
        patterns.append([special_color] * interior_cols)
        pattern_mid = [8] * side + [special_color] * middle + [8] * side
        patterns.append(pattern_mid)
        patterns.append([special_color] * interior_cols)
    elif num_parts == 4:
        if num_groups == 3:
            # Pattern: parts [0,1], [1,2], [0]
            patterns.append(make_pattern(0, 2))
            patterns.append(make_pattern(1, 2))
            patterns.append(make_pattern(0, 1))
        else:
            # Default
            for start in range(min(num_groups, num_parts - 1)):
                patterns.append(make_pattern(start, 2))
    elif num_parts == 2:
        # Default for 2 parts
        patterns.append(make_pattern(0, 2))
        patterns.append(make_pattern(0, 1))
        patterns.append(make_pattern(1, 1))

    # Ensure we have the right number of patterns
    while len(patterns) < num_groups:
        patterns.append([8] * interior_cols)
    patterns = patterns[:num_groups]

    # Build output interior
    output_interior = []
    for pattern in patterns:
        for _ in range(rows_per_group):
            output_interior.append(pattern[:])

    # Add frame border
    result = []
    result.append([frame_color] * (interior_cols + 2))
    for row in output_interior:
        result.append([frame_color] + row + [frame_color])
    result.append([frame_color] * (interior_cols + 2))

    return result
